### Numpy数据类型

In [1]:
import numpy as np
dt = np.dtype(np.int32)
print(dt)
print(type(dt))

int32
<class 'numpy.dtypes.Int32DType'>


In [2]:
import numpy as np
dt = np.dtype('i4')
print(dt)
print(type(dt))

int32
<class 'numpy.dtypes.Int32DType'>


In [3]:
import numpy as np
dt = np.dtype('<i4')
print(dt)
print(type(dt))

int32
<class 'numpy.dtypes.Int32DType'>


In [ ]:
import numpy as np
student = np.dtype([("name", "S20"), ("age", "i4"), ("grade", "f4")])
print(student)
print(type(student))

[('name', 'S20'), ('age', '<i4'), ('marks', '<f4')]
<class 'numpy.dtypes.VoidDType'>


### array()函数

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 元素类型不同，优先级
import numpy as np
arr = np.array([1, 2, 3, 4.5, 5])
print(arr)

[1.  2.  3.  4.5 5. ]


In [4]:
# 多维数组
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#ndmin
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], ndmin=2)
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [9]:
# dtype参数
arr = np.array([1, 2, 3, 4, 5], dtype=np.float32)
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [10]:
# dtype参数
arr = np.array([1, 2, 3, 4, 5], dtype='f')
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [13]:
# 结构化数据类型
student = np.dtype([("name", "S20"), ("age", "i4"), ("marks", "f4")])
arr = np.array([("capybara", 18, 99.99), ("spicypig", 19, 97.77)], dtype=student)
arr

array([(b'capybara', 18, 99.99), (b'spicypig', 19, 97.77)],
      dtype=[('name', 'S20'), ('age', '<i4'), ('marks', '<f4')])

### asarray()

In [14]:
import numpy as np
x = [1,2,3,4,5]
arr = np.asarray(x)
print(arr)

[1 2 3 4 5]


In [15]:
import numpy as np
arr = np.empty([3, 2], dtype=int)
#数组元素为随机值，因为它们未初始化arr
print(arr)

[[25895968440320000               800]
 [                0     2621628243216]
 [                0 13792707650584833]]


### zeros函数

In [22]:
import numpy as np
arr = np.zeros(5, dtype='i4')
print(arr)

[0 0 0 0 0]


In [ ]:
import numpy as np
arr = np.zeros([3,2])
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
import numpy as np
arr = np.zeros([2,2], dtype=[('x', 'i4'), ('y', 'f4')])
print(arr)

[[(0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.)]]
